//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademList
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcadList
    {
        public int Id { get; set; }
        public int Rating_Id { get; set; }
        public int Lab_Id { get; set; }
        public int Exam_Id { get; set; }
        public int Counter { get; set; }
        public string Student_Id { get; set; }
        public int Pattern_Id { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Labs Labs { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Pattern Pattern { get; set; }
    }
}
