//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Labs()
        {
            this.AcadList = new HashSet<AcadList>();
        }
    
        public int Id { get; set; }
        public int FirstLab { get; set; }
        public int SecondLab { get; set; }
        public int ThirdLab { get; set; }
        public int FourthLab { get; set; }
        public int FifthLab { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcadList> AcadList { get; set; }
    }
}
